language: cpp
sudo: required

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/deps

services:
  - docker

matrix:
  include:
    - os: linux
      env:
        - OS_TYPE=ubuntu_docker
        - OS_VERSION=bionic
    - os: linux
      dist: xenial
      env:
        - OS_TYPE=doxygen
      addons: { apt: { packages: ["cmake", "graphviz"] } }
    - compiler: "gcc"
      os: osx
      osx_image: xcode10.1
      env:
        - EXTRA_SSH=-oHostKeyAlgorithms=+ssh-dss
    - compiler: "gcc"
      os: osx
      osx_image: xcode11
      env:
        - EXTRA_SSH=-oHostKeyAlgorithms=+ssh-dss

before_install:

  - export DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR}

  # Configure git user for Travis to push documentation
  - git config --global user.name "Travis Bot"
  - git config --global user.email "<>"

  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./CI/travis/before_install_darwin ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./CI/travis/before_install_linux "$OS_TYPE" "$OS_VERSION" ; fi

  - mkdir -p $TRAVIS_BUILD_DIR/build
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mkdir -p $TRAVIS_BUILD_DIR/build_tar ; fi

script:
  - if [[ -z "$ARCH" && "$TRAVIS_OS_NAME" == "linux" ]]; then ${TRAVIS_BUILD_DIR}/CI/travis/make_linux libm2k "$OS_TYPE" "$OS_VERSION" ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ${TRAVIS_BUILD_DIR}/CI/travis/make_darwin; fi

before_deploy:
  - if [[ ($OS_TYPE != doxygen) ]]; then . ${TRAVIS_BUILD_DIR}/CI/travis/before_deploy; fi

deploy:
  - provider: releases
    api_key:
      secure: buLwkQXbmIREOC1yTL1cVaZW4bbZ2lUajcKzIG64ius+uGxesru8UMVMjCEqYSMDH+NMzuY5QMMrzvRPuc5yjo/0p/t5O2YT5pikt0YJu2jTwvnXtMnhXOQCqk/nHa9t4pJza2WkqTov1BYv7xdYCYexG6dK27IMZd3zMKd3PnRzUe9RBum3mNZrYBpx1QLqaoDjZ9TLZDLLhrAoK7qU0vRTXMEnEYTtCJIYlloo/TQt9dSFEQiUdMfiRp23exDzUlYFmiut3RfvDTuZT1TaLjP8P+zT8sgc10ypxDct2+pOMUfNP/8ZWCTQ5trcfMmyxxKWPn4I2Qy3IyrFBInZwu5C5PxR+DGfsmqofqbN+rbDOhkYljbYH5hn1zmhws3WdU0sRGwbrNQ8LtJ1QEn2SXkx1PZYkjvFMv4LfkI3SxMvuqNNnHKqBa3ovTw7obyvpUb6katX28ampDxTIiXOo1QtOLTz6cxncrT2RnUD3ROK/iS8jJWh+Hnyu9YxAfb1dRWpOXRFBO6XB5++zT/rsU9Q/QyxUV8C6VWY0FvQoFJfeS62OYcxU4g+qnKOPinoLrSO1rnVjVDpudGweQ+ks9IN6/o1tJpt7Xj6zs/BPfCtKr2lZwxYREgfVuTpMXpCbSMdAxdOAxigjuEexwS2vchFu0s4luKRu8Bpq+Hob+M=
    file:
      - "${RELEASE_PKG_FILE_DEB}"
      - "${RELEASE_PKG_FILE_RPM}"
      - "${RELEASE_PKG_FILE_TGZ}"
    skip_cleanup: true
    on:
      all_branches: true
      repo: AlexandraTrifan/libm2k
      condition: "($OS_TYPE != doxygen) && ($TRAVIS_OS_NAME = linux)"
    draft: true

  - provider: releases
    api_key:
      secure: buLwkQXbmIREOC1yTL1cVaZW4bbZ2lUajcKzIG64ius+uGxesru8UMVMjCEqYSMDH+NMzuY5QMMrzvRPuc5yjo/0p/t5O2YT5pikt0YJu2jTwvnXtMnhXOQCqk/nHa9t4pJza2WkqTov1BYv7xdYCYexG6dK27IMZd3zMKd3PnRzUe9RBum3mNZrYBpx1QLqaoDjZ9TLZDLLhrAoK7qU0vRTXMEnEYTtCJIYlloo/TQt9dSFEQiUdMfiRp23exDzUlYFmiut3RfvDTuZT1TaLjP8P+zT8sgc10ypxDct2+pOMUfNP/8ZWCTQ5trcfMmyxxKWPn4I2Qy3IyrFBInZwu5C5PxR+DGfsmqofqbN+rbDOhkYljbYH5hn1zmhws3WdU0sRGwbrNQ8LtJ1QEn2SXkx1PZYkjvFMv4LfkI3SxMvuqNNnHKqBa3ovTw7obyvpUb6katX28ampDxTIiXOo1QtOLTz6cxncrT2RnUD3ROK/iS8jJWh+Hnyu9YxAfb1dRWpOXRFBO6XB5++zT/rsU9Q/QyxUV8C6VWY0FvQoFJfeS62OYcxU4g+qnKOPinoLrSO1rnVjVDpudGweQ+ks9IN6/o1tJpt7Xj6zs/BPfCtKr2lZwxYREgfVuTpMXpCbSMdAxdOAxigjuEexwS2vchFu0s4luKRu8Bpq+Hob+M=
    file:
      - "${RELEASE_PKG_FILE_PKG}"
      - "${RELEASE_PKG_FILE_TGZ}"
    skip_cleanup: true
    on:
      all_branches: true
      repo: AlexandraTrifan/libm2k
      condition: "$TRAVIS_OS_NAME = osx"
    draft: true
