language: cpp
sudo: required

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/deps

services:
  - docker

env:
  global:
    secure: "PUXsXOrIGEZMK78hPI2do7FRLr1qB/jS/cXPOgVEHT/iJYU9hzu5BkJHjRLKZ7uM6L+17FM3OVJFsWk68Rcql7pT79G1nI6l0RyqsazMdgDDed2FlxxmvRmHuRT6ONqvBEDSItkIn16Y2ld+UukG36bLSVYyuc5NaMBV/cB8kyBgq41rf+jBvrGvsBV5aN73ZWqMwCqNsRLhwGRqhJlGcPsAc0j957O3fzEeTRF9SMVczpMt8fGFD/2R2gyyX50zX2YTRAT9d7kyl/IFi9GtIYQs/afIQ1hYDzWK+bYpHozoiSYHfs8YBYdtFItj2P3h2XsZgG9t4FlLInF7phCTftRTTB+G6eT0N8mOPi+uCXR1m9lU7TF5rKhL7Yg+KTQiHFfDxHzPrzmKht06b7lCuMfY7nBgmJXEZOtDFuhPdxubu3TD4DRtn36NyW1PPMOBI/guii1ywrlWl0HeKciaRlPHbP0RB+s0eBWWzVpiJVveO1sO0MgtZ4/+v+REtqNAsD26iLGgvrahMMdw/dWTt3Niez93xrUSYVA9mnk/Dlc42y02+Okwu+Jw0GPnBCMq7snfYwZMFM2EN4waCaxbgPSNOvuLIfmLTWnpjMcVh2FtfP39jlBPymO9FYZyqlfZBc6mzFOEB9pVN1rMKPqk9cYFvcvY1sP10owVwFSWpIo="

matrix:
  include:
    - os: linux
      dist: bionic
      python: 3.6
      env:
        - PYTHON=python PIP=pip
    - os: linux
      dist: xenial
      python: 3.6
      env:
        - PYTHON=python PIP=pip
    - os: linux
      dist: xenial
      env:
        - OS_TYPE=doxygen
      addons: { apt: { packages: ["cmake", "graphviz"] } }
    - compiler: "gcc"
      os: osx
      osx_image: xcode10.1
      env:
        - EXTRA_SSH=-oHostKeyAlgorithms=+ssh-dss
    - compiler: "gcc"
      os: osx
      osx_image: xcode11
      env:
        - EXTRA_SSH=-oHostKeyAlgorithms=+ssh-dss

before_install:

  - export DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR}

  # Configure git user for Travis to push documentation
  - git config --global user.name "Travis Bot"
  - git config --global user.email "<>"

  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./CI/travis/before_install_darwin ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./CI/travis/before_install_linux "$OS_TYPE" "$OS_VERSION" ; fi

  - mkdir -p $TRAVIS_BUILD_DIR/build
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mkdir -p $TRAVIS_BUILD_DIR/build_tar ; fi

script:
  - if [[ -z "$ARCH" && "$TRAVIS_OS_NAME" == "linux" ]]; then ${TRAVIS_BUILD_DIR}/CI/travis/make_linux libm2k "$OS_TYPE" "$OS_VERSION" ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ${TRAVIS_BUILD_DIR}/CI/travis/make_darwin; fi
before_deploy:
  - ". ${TRAVIS_BUILD_DIR}/CI/travis/before_deploy"

deploy:
  - provider: releases
    api_key:
      secure: FCGbxC6aaYKWCP9/nU0TpJyGxEs0gnaHv5Oz6jZYZa2MyjU6l3ustAE/j+kS5KutaBKV6Kw01W5xjJ7mmUpmQDlDqe8VJJubiRy36sAy5mlxhi6zZZH0pxoVJmtVcAIO0xmBWrikYCS5FiZE9Ma7T35k27lIlwhSnB2vfR2ELsbJJ7vPC7wPmNa+nRpSQF96iaOfNCvTxLDB51ZDKPeBOTo68qQGOM/gOWYPJRDRdxoNe97b8x/sAf5sCD4EAM2IrqHepe/PZ1M/aTDuIRDn3WUGuwVJCSyHOvdBJ5s4L8a90beU1c2mGJDTZXugLuf66QR35RaZjgGskIbPIqNz1REEj1eMqgF/hMzPUZSpy1JwBV9ZMpOAK1v8HXG7ics2qZfhPZP7WuvH4ZB5NJt5A9zkYOqlBqTFDXVTaG8KZFvED+9HQtsXq5v0VUbHPpRT4sA9erve9tOOUexSEvGbLo104mcpKB6NmdmP1Elg+bIIVLHQNeYZ03e3wRQAG2xIJY7HnHl4sODmwW1SCfS89nqYOvUa6HNTWTzprGX8pclF614Qncpa42XmE5XXwNRm9yQMG9FHhoQQ7sQ3iTzqadtYuTwqRL9S8q4g8RVY6UGc6jR02ZGnaEuxDBVQf1z/cxecMzXXEiHxi6a8qsLp4M3mXDuwcO5rG+WkfBKbKbc=
    file:
      - "${RELEASE_PKG_FILE_DEB}"
      - "${RELEASE_PY_FILE_DEB}"
      - "${RELEASE_PKG_FILE_TGZ}"
    skip_cleanup: true
    on:
      repo: AlexandraTrifan/libm2k
      tags: true
      condition: "($TRAVIS_OS_NAME = linux) && ($OS_TYPE != doxygen)"
  - provider: releases
    api_key:
      secure: FCGbxC6aaYKWCP9/nU0TpJyGxEs0gnaHv5Oz6jZYZa2MyjU6l3ustAE/j+kS5KutaBKV6Kw01W5xjJ7mmUpmQDlDqe8VJJubiRy36sAy5mlxhi6zZZH0pxoVJmtVcAIO0xmBWrikYCS5FiZE9Ma7T35k27lIlwhSnB2vfR2ELsbJJ7vPC7wPmNa+nRpSQF96iaOfNCvTxLDB51ZDKPeBOTo68qQGOM/gOWYPJRDRdxoNe97b8x/sAf5sCD4EAM2IrqHepe/PZ1M/aTDuIRDn3WUGuwVJCSyHOvdBJ5s4L8a90beU1c2mGJDTZXugLuf66QR35RaZjgGskIbPIqNz1REEj1eMqgF/hMzPUZSpy1JwBV9ZMpOAK1v8HXG7ics2qZfhPZP7WuvH4ZB5NJt5A9zkYOqlBqTFDXVTaG8KZFvED+9HQtsXq5v0VUbHPpRT4sA9erve9tOOUexSEvGbLo104mcpKB6NmdmP1Elg+bIIVLHQNeYZ03e3wRQAG2xIJY7HnHl4sODmwW1SCfS89nqYOvUa6HNTWTzprGX8pclF614Qncpa42XmE5XXwNRm9yQMG9FHhoQQ7sQ3iTzqadtYuTwqRL9S8q4g8RVY6UGc6jR02ZGnaEuxDBVQf1z/cxecMzXXEiHxi6a8qsLp4M3mXDuwcO5rG+WkfBKbKbc=
    file:
      - "${RELEASE_PKG_FILE_PKG}"
      - "${RELEASE_PKG_FILE_TGZ}"
    skip_cleanup: true
    on:
      repo: AlexandraTrifan/libm2k
      tags: true
      condition: "$TRAVIS_OS_NAME = osx"
